#org.gradle.jvmargs=-Xmx1536M
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=33210
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=33210
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=9888
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=9888
